#!/bin/bash
# At the end of the day, scan the logs of planet/universe,
# grep for errors, sort them, count the duplicate URLs
# and email the planet admins with the result

for instance in planet universe; do
    find /var/log/planet.gentoo.org/${instance} -type f -name "$(date +%Y-%m-%d)*" -exec grep "ERROR" {} \; | sort | uniq -c
done
